global using Fun;
global using static Fun.Extensions;
global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Linq;
global using System.Text;
global using MathematicalProgramming.Helpers;
global using S = MathematicalProgramming.Helpers.Singletons;
global using static MathematicalProgramming.Helpers.HelperExtensions;
