global using Fun;
global using static Fun.Extensions;
global using System;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Linq;
global using System.Text;
global using static MathematicalProgramming.Extensions;
global using MathematicalProgramming;
//global using MathematicalProgrammingCplex;
